export const ERROR_CODES = {
  AUTH_ERROR: "AUTH_ERROR",
  TIER_LIMIT: "TIER_LIMIT",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RETRIEVAL_ERROR: "RETRIEVAL_ERROR",
  INGESTION_ERROR: "INGESTION_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
